remove rb-kqueue
[Browsersync] Watching files...
E, [2020-01-29T07:52:33.918173 #77214] ERROR -- : run() in thread failed: undefined method `callback!' for nil:NilClass:\n /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/event.rb:80:in `callback!'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `block in process'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `each'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `process'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:316:in `run'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/adapter/bsd.rb:50:in `_run'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/adapter/base.rb:78:in `block in start'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /usr/local/lib/ruby/2.6/forwardable.rb:230:in `start'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/listener.rb:68:in `block in <class:Listener>'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/fsm.rb:121:in `instance_eval'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/fsm.rb:121:in `call'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/fsm.rb:57:in `transition'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/listener.rb:91:in `start'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:26:in `watch'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:88:in `watch'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:43:in `process'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-browsersync-1.0.0/lib/jekyll-browsersync/command.rb:49:in `process'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-browsersync-1.0.0/lib/jekyll-browsersync/command.rb:19:in `block (2 levels) in init_with_program'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
/home/trombik/.vendor/bundle/ruby/2.6/bin/jekyll:23:in `load'
/home/trombik/.vendor/bundle/ruby/2.6/bin/jekyll:23:in `<main>'
Traceback (most recent call last):
	7: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/internals/thread_pool.rb:6:in `block in add'
	6: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/adapter/base.rb:78:in `block in start'
	5: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/listen-3.2.1/lib/listen/adapter/bsd.rb:50:in `_run'
	4: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:316:in `run'
	3: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `process'
	2: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `each'
	1: from /usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/queue.rb:337:in `block in process'
/usr/home/trombik/.vendor/bundle/ruby/2.6/gems/rb-kqueue-0.2.5/lib/rb-kqueue/event.rb:80:in `callback!': undefined method `callback!' for nil:NilClass (NoMethodError)